### ISSUE TITLE
ca985980dea558c4bf0255584e2c2f34801604aa breaks the -j ".!no tests here!" magic

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.testrunner#27] opened 2015-05-19 06:55 UTC
https://github.com/zopefoundation/zope.testrunner/commit/ca985980dea558c4bf0255584e2c2f34801604aa

@mgedmin says:
if -j is present on the command line, create a fake test layer inside the test runner itself, then insert it in front

**Comment by mgedmin** [comment] 2015-05-19 06:57
Duplicate of #28 which I was filing at the same time.  I like my description better so I'll close this one.

**Closed by mgedmin** 2015-05-19 06:57 UTC
