### ISSUE TITLE
Is it possible to share a layer between multiple TestCase's?

### ISSUE THREAD

**Issue by ksuess** [zopefoundation/zope.testrunner#132] opened 2022-04-22 08:17 UTC
Reason to ask is that I want to use Sybil https://sybil.readthedocs.io/en/latest/index.html for plone.api.
Sybil would help to evaluate and test code blocks in documentation files.
Sybil unfortunatly creates one TestCase for each code block in a documentation file. So I cannot do something like

````

```{eval-rst}
.. module:: plone
    :noindex:
```


## Create content

To add an object, you must first have a container to put it in.
Get the portal object; it will serve nicely:

```python
from plone import api
portal = api.portal.get()
```

Create your new content item using the {meth}`api.content.create` method.
The type argument will decide which content type will be created.

```python
from plone import api
obj = api.content.create(
    type='Document',
    title='My Content',
    container=portal)
self.assertEqual(obj.id, 'my-content')
self.assertEqual(portal['my-content'].id, 'my-content')
```

Check in another code block:

```python
# self.assertEqual(obj.id, 'my-content')
self.assertEqual(api.content.get(path='/my-content').id, 'my-content')
self.assertEqual(portal['my-content'].id, 'my-content')
```
````

**Comment by d-maurer** [comment] 2022-04-22 08:46
Katja Süss wrote at 2022-4-22 01:17 -0700:
> ...

You typically have:
```python
class Layer:
    @classmethod
    def setUp(cls):
        ...

    @classmethod
    def tearDown(cls):
        ...


class Tests1(TestCase):
    layer = Layer
    ...

class Tests2(TestCase):
    layer = Layer
    ...
```

Thus, it is common that layers are shared between several
`TestCase`s.


Note that `Plone` usually uses (class) instances (rather then classes
themselves) as layers (but this should not be relevant for your
question).


Your problem might be how tell `sybil` what layer to use.

**Comment by mauritsvanrees** [comment] 2022-04-29 07:09
I think the problem is that Sybil translates the document into roughly this:

```
class Tests1(TestCase):
    layer = Layer

    def test1(self):
        from plone import api
        portal = api.portal.get()

    def test2(self):
        from plone import api
        obj = api.content.create(
            type='Document',
            title='My Content',
            container=portal)
        self.assertEqual(obj.id, 'my-content')
        self.assertEqual(portal['my-content'].id, 'my-content')

    def test3(self):
        self.assertEqual(api.content.get(path='/my-content').id, 'my-content')
        self.assertEqual(portal['my-content'].id, 'my-content')
```

The tests will share the same TestCase class and the same layer. But all code blocks are run in separate test methods: anything done in `test1` or `test2` is unavailable in `test3`.

Theoretically, if you could somehow avoid automatically calling `self.tearDown` after each test method, it should work. And then you *must* call `self.tearDown` after the _last_ test method. Sounds tricky.

**Comment by icemac** [comment] 2022-12-06 10:29
Closing a `wontfix` as there is no solution inside this repository for this issue.
Please re-open if you disagree.

**Closed by icemac** 2022-12-06 10:29 UTC
Labels: wontfix
